workspace = { members = [ "amuse","muse-ui"] }

[package]
name = "muse"
version = "0.1.0"
edition = "2021"


[dependencies]
ahash = "0.8.7"
crossbeam-utils = "0.8.19"
interner = "0.2.1"
kempt = { version = "0.2.3", features = ["serde"] }
serde = { version = "1.0.195", features = ["derive"] }
unicode-ident = "1.0.12"

[dev-dependencies]
rsn = "0.1"
pollster = "0.3.0"
flume = "0.11.0"

[lints.clippy]
pedantic = "warn"
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[lints.rust]
unsafe_code = "forbid"


[[test]]
name = "harness"
harness = false
