name: Tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: ["stable", "1.79.0"]
        features: ["", "--all-features"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version }}

      - name: Run clippy
        if: matrix.version == 'stable'
        run: |
          cargo clippy ${{ matrix.features }} --all-targets -p muse

      - name: Build
        run: |
          cargo build ${{ matrix.features }} --all-targets -p muse

      - name: Run unit tests
        run: |
          cargo test ${{ matrix.features }} --all-targets -p muse -- --nocapture